services:
  - type: web
    name: job-matcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=${PORT}
    healthCheckPath: /
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: TOKENIZERS_PARALLELISM
        value: false
